apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ohif-dcm4chee.fullname" . }}-arc
  labels:
    {{- include "ohif-dcm4chee.labels" . | nindent 4 }}
    app: {{ include "ohif-dcm4chee.fullname" . }}-arc
spec:
  selector:
    matchLabels:
      {{- include "ohif-dcm4chee.selectorLabels" . | nindent 6 }}
      app: {{ include "ohif-dcm4chee.fullname" . }}-arc
  template:
    metadata:
      labels:
        {{- include "ohif-dcm4chee.selectorLabels" . | nindent 8 }}
        app: {{ include "ohif-dcm4chee.fullname" . }}-arc
    spec:
      containers:
        - name: arc
          image: dcm4che/dcm4chee-arc-psql:5.25.2
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: HTTPS_PORT
              value: "8443"
            - name: MANAGEMENT_HTTP_PORT
              value: "9990"
            - name: MANAGEMENT_HTTPS_PORT
              value: "9993"
            - name: LDAP_URL
              value: ldap://{{ include "ohif-dcm4chee.fullname" . }}-ldap:389
            # - name: AUTH_SERVER_URL
              # value: https://{{ include "ohif-dcm4chee.fullname" . }}-keycloak:8843/auth
            - name: WILDFLY_CHOWN
              value: /opt/wildfly/standalone /storage
            - name: WILDFLY_WAIT_FOR
              value: {{ include "ohif-dcm4chee.fullname" . }}-ldap:389 {{ include "ohif-dcm4chee.fullname" . }}-postgres:5432 # {{ include "ohif-dcm4chee.fullname" . }}-logstash:8514
            - name: JAVA_OPTS
              value: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=*:8787,server=y,suspend=n
            - name: POSTGRES_HOST
              value: {{ include "ohif-dcm4chee.fullname" . }}-postgres
            # - name: LOGSTASH_HOST
            #   value: {{ include "ohif-dcm4chee.fullname" . }}-logstash
          envFrom:
            - secretRef:
                name: {{ include "ohif-dcm4chee.fullname" . }}-ldap-secret
            - secretRef:
                name: {{ include "ohif-dcm4chee.fullname" . }}-postgres-secret
          ports:
            - containerPort: 8080
            - containerPort: 8443
            - containerPort: 9990
            - containerPort: 9993
            - containerPort: 8787
            - containerPort: 11112
            - containerPort: 2762
            - containerPort: 2575
            - containerPort: 12575
          volumeMounts:
            # - name: localtime
            #   mountPath: /etc/localtime
            #   readOnly: true
            # - name: timezone
            #   mountPath: /etc/timezone
            #   readOnly: true
            - name: wildfly
              mountPath: /opt/wildfly/standalone
            - name: storage
              mountPath: /storage
      volumes:
        # - name: localtime
        #   hostPath:
        #     path: /etc/localtime
        #     type: File
        # - name: timezone
        #   hostPath:
        #     path: /etc/timezone
        #     type: File
        - name: wildfly
          emptyDir: {}
          # hostPath:
          #   path: /var/local/microk8s/wildfly
          #   type: DirectoryOrCreate
        - name: storage
          emptyDir: {}
          # hostPath:
          #   path: /var/local/microk8s/storage
          #   type: DirectoryOrCreate
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}