apiVersion: v1
kind: Service
metadata:
  name: {{ include "ohif-dcm4chee.fullname" . }}-ldap
  labels:
    {{- include "ohif-dcm4chee.labels" . | nindent 4 }}
    app: {{ include "ohif-dcm4chee.fullname" . }}-ldap
spec:
  clusterIP: None
  selector:
    app: {{ include "ohif-dcm4chee.fullname" . }}-ldap
  ports:
    - name: ldap
      port: 389
    - name: ldaps
      port: 636