apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohif-dcm4chee.fullname" . }}-ldap-secret
  labels:
    {{- include "ohif-dcm4chee.labels" . | nindent 4 }}
data:
  LDAP_ROOTPASS: {{ .Values.ldap.rootPass | b64enc | quote}}
  LDAP_CONFPASS: {{ .Values.ldap.confPass | b64enc | quote}}
type: Opaque