apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ohif-dcm4chee.fullname" . }}-ohif
  labels:
    {{- include "ohif-dcm4chee.labels" . | nindent 4 }}
    app: {{ include "ohif-dcm4chee.fullname" . }}-ohif
spec:
  selector:
    matchLabels:
      {{- include "ohif-dcm4chee.selectorLabels" . | nindent 6 }}
      app: {{ include "ohif-dcm4chee.fullname" . }}-ohif
  template:
    metadata:
      labels:
        {{- include "ohif-dcm4chee.selectorLabels" . | nindent 8 }}
        app: {{ include "ohif-dcm4chee.fullname" . }}-ohif
    spec:
      containers:
      - name: ohif-container
        image: ohif/viewer:v4.12.22.18589
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        # - name: nginx-config
        #   mountPath: /etc/nginx/conf.d
        - name: ohif-config
          mountPath: /usr/share/nginx/html/app-config.js
          subPath: app-config.js
      volumes:
      # - name: nginx-config
      #   configMap:
      #     name: {{ include "ohif-dcm4chee.fullname" . }}-nginx
      - name: ohif-config
        configMap:
          name: {{ include "ohif-dcm4chee.fullname" . }}-ohif

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}