apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohif-dcm4chee.fullname" . }}-postgres-secret
  labels:
    {{- include "ohif-dcm4chee.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ "pacsdb" | b64enc | quote}}
  POSTGRES_USER: {{ "pacs" | b64enc | quote}}
  POSTGRES_PASSWORD: {{ .Values.postgres.pass | b64enc | quote}}
type: Opaque